### ISSUE TITLE
ChestItems

### ISSUE THREAD

**Issue by uselesswaifu** [JackMD/MysteryCrate#1]
Every slot of the chest items are random. This makes the whole point of having them in a line obsolete. The whole idea is that you will see what you could've got but missed. I suggest only making Slot #16 random (https://github.com/JackMD/MysteryCrate/blob/master/src/JackMD/MysteryCrate/UpdaterEvent.php#L95)
(Make them all random the first time the code is executed.)

and then the next time the code is executed again make slot #16 item equal slot #15 item.
Then make slot #16 a random item again.

```
$this->setItem(14, $this->chest->getInventory()->getSlot(15)->getItem()->getId(), 1);
$this->setItem(15, $this->chest->getInventory()->getSlot(16)->getItem()->getId(), 1);
$this->setItem(16, $this->ids[(int)rand(0, 18)], 1);
```

This is just an example. ^ I am not sure if such a function exist.

**Comment by JackMD** [comment]
This is now fixed. Thanks for reporting.

**Comment by uselesswaifu** [comment]
I think I explained this problem incorrectly.
What should happen is a new item starts at the right and moves over to the left. (Starts at slot 15. Then goes to slot 14, then 13, etc..)

**Comment by JackMD** [comment]
@uselesswaifu I get what you are trying to say but upon doing that what ends up happening is the Item at slot 16 gets copied to all the other slots and when it changes (the item at slot 16) other slots change as well.
You can test this for yourself. Replace this [line](https://github.com/JackMD/MysteryCrate/blob/01d2c1658196d0875003e6e5e98b0a6213d87d14/src/JackMD/MysteryCrate/UpdaterEvent.php#L94) with 
`$this->setItem(15, $this->chest->getInventory()->getItem(16)->getId(), 1);`
Hope that solved your problem.

**Comment by uselesswaifu** [comment]
@JackMD I was sending an example, I was just suggesting such a feature gets added. The problem you suggested would not occur if you code it correctly.

**Comment by JackMD** [comment]
I do agree but currently I have other plans. Might do so in future along with making a separate `items.yml` file.

**Comment by uselesswaifu** [comment]
I hope it all works out 💃

**Comment by JackMD** [comment]
@uselesswaifu I might have found a solution for your suggestion. Testing it before releasing.

**Comment by uselesswaifu** [comment]
I’d be happy to see it.

**Comment by JackMD** [comment]
The feature has been added in 147d164
