### ISSUE TITLE
Um.. ?

### ISSUE THREAD

**Issue by AmeerReal** [JackMD/MysteryCrate#105]
[Server thread/CRITICAL]: ErrorException: "Undefined index: broadcast" (EXCEPTION) in "plugins/MysteryCrate.phar/src/JackMD/MysteryCrate/Main" at line 115
[Server thread/DEBUG]: #0 plugins/MysteryCrate.phar/src/JackMD/MysteryCrate/Main(115): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined index: broadcast, string phar:///home/minecraft/plugins/MysteryCrate.phar/src/JackMD/MysteryCrate/Main.php, integer 115, array Array())
[Server thread/DEBUG]: #1 plugins/MysteryCrate.phar/src/JackMD/MysteryCrate/Main(89): JackMD\MysteryCrate\Main->initCrates()
[Server thread/DEBUG]: #2 src/pocketmine/plugin/PluginManager(193): JackMD\MysteryCrate\Main->onLoad()
[Server thread/DEBUG]: #3 src/pocketmine/plugin/PluginManager(343): pocketmine\plugin\PluginManager->loadPlugin(string /home/minecraft/plugins/MysteryCrate.phar, array Array())
[Server thread/DEBUG]: #4 src/pocketmine/Server(1718): pocketmine\plugin\PluginManager->loadPlugins(string /home/minecraft/plugins/)
[Server thread/DEBUG]: #5 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/, string /home/minecraft/plugins/)
[Server thread/DEBUG]: #6 (1): require(string phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php
[Server thread/CRITICAL]: Could not load plugin 'MysteryCrate'

**Comment by JackMD** [comment]
Use the pattern that is shown in the crates.yml. the `broadcast:` key is must. Make sure you copy it.
