### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by A354-PH** [JackMD/MysteryCrate#106]
When I open my server, this error shows
`[23:43:15] [Server thread/CRITICAL]: ErrorException: "Undefined index: broadcast" (EXCEPTION) in "plugins/MysteryCrate v8.0.1.phar/src/JackMD/MysteryCrate/Main" at line 115` 

Please fix it

**Comment by JackMD** [comment]
You fix your crates.yml. Things have changed so update it
