### ISSUE TITLE
Please fix this error

### ISSUE THREAD

**Issue by SnailCrazy** [JackMD/MysteryCrate#114]
I just try update my server using PM 3.6.2 but there something wrong with create i made

this just short my config reward money
      - name: "Rp 100"
        id: 339
        meta: 50
        amount: 1
        commands:
          - "givemoney \"%PLAYER%\" 100"
          - "bcast \"%PLAYER%\" mendapat Rp 100"

when i am using PM 3.5.1 run well, but when run using PM 3.6.2 money become an item and directly insert into inventory

**Comment by JackMD** [comment]
**Go and read the data in `crates.yml` file!!** 


I won't telll you what's wrong. Figure out urself.

**Comment by JackMD** [comment]
Anyways. Instead of using ""%PLAYER%" use **\"%PLAYER%\"**.

And do read the examples in crates.yml.
