### ISSUE TITLE
You can take items from crates when you are opening

### ISSUE THREAD

**Issue by mikeygio10** [JackMD/MysteryCrate#118]
Sorry for giving you a bad review i was just upset because you are the only good crate plugin

**Comment by JackMD** [comment]
Please elaborate. Explain in detail whats wrong. Give me steps on how to reproduce it.

**Comment by mikeygio10** [comment]
Well i open the crate and i grab items from crate

**Comment by JackMD** [comment]
Blame pocketmine or mojang for not restricting transactions even when cancelled!

Not the fault this plugin nor is it a bug with this plugin!! Also the item if taken gets removed later on or when you try to use it
