### ISSUE TITLE
Crates make chests not work?

### ISSUE THREAD

**Issue by 0pGam3rMC** [JackMD/MysteryCrate#12]
When I place a chest under the floating texts. The crates work fine, but then other chests do not allow you to place items in them.🤔

**Comment by JackMD** [comment]
I am aware of that and have purposely made it so. To avoid that make a new world with the crate only. You could call that world Crate. And this happens only when the task is running i.e. the crate is operating.

**Comment by JackMD** [comment]
I will be making a fix for that issue but that is of low priority and until then I am closing the issue.

**Comment by JackMD** [comment]
Fixed in [86dd8bb](https://github.com/JackMD/MysteryCrate/commit/86dd8bb554fd70f7527a06226511b8cb8ec8b1d3)
