### ISSUE TITLE
Can't retrieve crate keys from crates that have a name with uppercase characters

### ISSUE THREAD

**Issue by AndreasHGK** [JackMD/MysteryCrate#120]
**Reproduce:** 
- make a new crate with an uppercase name in crates.yml
- start the server, place the crate and restart the server
- do /keyall or /key with the correct name with or without uppercase
- it doesn't work. It says that the crate doesn't exist.

**Pluign version:** v9.1.0
**Pocketmine version:** 3.7.1

This happens because you first make the name lowercase in both commands:
https://github.com/JackMD/MysteryCrate/blob/a4402559c655cf6a656146573ce1064d19db8876/src/JackMD/MysteryCrate/command/KeyAllCommand.php#L73
After that, you compare the name to a possibly uppercase crate in crates.yml
https://github.com/JackMD/MysteryCrate/blob/a4402559c655cf6a656146573ce1064d19db8876/src/JackMD/MysteryCrate/Main.php#L319

**Comment by JackMD** [comment]
Yes I have been aware of this bug for quite some time now but I have the time right now to fix it.

**Comment by JackMD** [comment]
I mean I know how to fix this but the reality is I have lost motivation working on this plugin.. In its current form this is one giant piece of 💩... And I cba to fix it...

**Comment by JackMD** [comment]
Didnt meant to close...

**Comment by AndreasHGK** [comment]
sounds familiar

**Comment by JackMD** [comment]
yep

**Comment by JackMD** [comment]
Eh closing in favor of archiving. And i have no plans on maintaining this.
