### ISSUE TITLE
How do I add names to the items?

### ISSUE THREAD

**Issue by Bruth78** [JackMD/MysteryCrate#121]
Hello.
I've copied the Vote Crate format for more than one item for the Common Crate but whenever i try to add: '- name:' it won't work. Or like commands, a lore or a broadcast.
Ik there's probably an easy way of fixing it but i can't find it.
![image](https://user-images.githubusercontent.com/46278674/55905863-3c55e500-5bd3-11e9-92a5-b7e4400fbbe3.png)
Great Plugin btw!
Thank you.

**Comment by JackMD** [comment]
Please read the 'Example Configuration' in crates.yml
