### ISSUE TITLE
World Won’t Work

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [JackMD/MysteryCrate#125]
So when I finish everything in the plugin and go to start my server it say “World “world” not found”. So I changed it to the name of the World and still doesn’t work saying the same thing. I’m using an app called Plug Pocketmine for Minecraft on the App Store.

**Comment by JackMD** [comment]
Are you sure that you are mentioning the right world name?

**Comment by Play2KillTV** [comment]
Try changing your world name

**Comment by JackMD** [comment]
Lack of response. Closing the issue. Further I am unable to reproduce it.
