### ISSUE TITLE
How do i put a kit inside a crate?

### ISSUE THREAD

**Issue by JammedMan** [JackMD/MysteryCrate#130]
I dont know how to put a kit inside a crate,can u tell me how to do it?btw i am bad at coding....well not that bad

**Comment by JackMD** [comment]
The same way you put an item with a command inside the chest.

**Comment by JammedMan** [comment]
Thx

Pada tanggal Min, 14 Jul 2019 02.37, Jack M. Taylor <
notifications@github.com> menulis:
