### ISSUE TITLE
Items Duplicate when the name a space have "Note Crafter"

### ISSUE THREAD

**Issue by note3crafter** [JackMD/MysteryCrate#137]
German :
Sobald man mit einem normalen Befehl /key Vote note3crafter bekommt man wie immer 1 Key aber sobald man /key Vote note crafter (mit einer Leertaste im namen) bekommt man das Ganze Inventar voller Keys ist das Normal kannst du das Fixen?

**Comment by Wertzui123** [comment]
Mach " vor un hinter den Namen! @note3crafter
