### ISSUE TITLE
unable to open mystery box for a non op player . 

### ISSUE THREAD

**Issue by teracube** [JackMD/MysteryCrate#15]
hi

sometimes the box remains blocked when a player tries to open it.
it happens when another player tried before him to open it

Pmmp dev 743
MysteryCrate dev 23

thanks

**Comment by JackMD** [comment]
I can't test this at the moment currently but if you are trying to access the crate when it is in use by another player the crate will remain closed for the second player until the first player closes the chest or the plugin itself removed the inventory window from the player.

**Comment by teracube** [comment]
@JackMD 
if a non op player win the stuff crate remain closed for all other non op players.
only a reload server solve this issue.
no problem with op players.

sorry for my bad english

**Comment by JackMD** [comment]
I will need to test that. Will do so shortly

**Comment by JackMD** [comment]
I tested it. Everything works. Further you can login here to test the plugin,
IP: 94 23.156.138
Port: 25630

**Comment by teracube** [comment]
@JackMD 
se this video on your server
a non op player can not open the crate. tested 2 times

https://drive.google.com/file/d/13il9-cAJ9QnijCpwb1evE8pCUnVcHw7H/view?usp=sharing

**Comment by JackMD** [comment]
That's very odd. Considering you used Windows 10 and I Android/ios everything worked fine for me on both platforms. Something is just not right at the moment. I will further investigate the issue. Thanks for reporting.

**Comment by JackMD** [comment]
Further in the video the chest inventory is not being opened. Something to do with PlayerInteractEvent.

**Comment by JackMD** [comment]
Nevermind it has happened to me too

**Comment by JackMD** [comment]
@teracube try using [this](https://poggit.pmmp.io/r/27574/MysteryCrate_pr-14.phar) and let me know if that fixes the issue.

**Comment by teracube** [comment]
@JackMD

It’s ok
tested with latest PMMP.phar v931 jenkins 
thank you

**Comment by JackMD** [comment]
Well that was an easy fix. Thanks for confirming. Report again of you have any issues.

**Comment by JackMD** [comment]
@teracube sorry for disturbing you but can you please confirm if #19 actually exists or not on the latest build. I am unable to test it currently. Help would be appreciated. Thanks

**Comment by JackMD** [comment]
Nvm i got it taken care of

**Comment by teracube** [comment]
@JackMD
sorry i was not at home

**Comment by JackMD** [comment]
No problem
