### ISSUE TITLE
Please resolv this bug.

### ISSUE THREAD

**Issue by dennisslol006** [JackMD/MysteryCrate#17]
I tried again but it still doesn't work.
It goes the first time and the second time says crate in use.
This time I only tried with ANDROID; It doesn't work either on the Pocketmine.

**Comment by JackMD** [comment]
That's very odd. I use Android and only PocketMine-MP. Everything works fine for me. But keep in mind that this plugin only supports PocketMine-MP and no other server fork/spoon. I will be investigating the issue.

**Comment by JackMD** [comment]
I tested it. Everything works. Further you can login here to test the plugin,
IP: 94 23.156.138
Port: 25630
