### ISSUE TITLE
Teaspoon Instead?

### ISSUE THREAD

**Issue by IonicSyz1823** [JackMD/MysteryCrate#23]
Could you possibly make this plugin work with teaspoon instead of vanilla enchant?

**Comment by JackMD** [comment]
okay I am going to be pushing some updates. I will add its compatibility too

**Comment by JackMD** [comment]
Fixed in [d47eaaa](https://github.com/JackMD/MysteryCrate/commit/d47eaaa4f6650faa805d9c957e13ce751f93a83d)
