### ISSUE TITLE
Piggy Custom Enchant

### ISSUE THREAD

**Issue by IonicSyz1823** [JackMD/MysteryCrate#26]
Don't support Piggy CE

Similar issue to this one:

https://github.com/DaPigGuy/PiggyCrates/issues/18

**Comment by JackMD** [comment]
I don't understand this completly. Are you talking about the enchants not working on the swords/armor/bows etc or the fact you can't give the ce book?

**Comment by IonicSyz1823** [comment]
If i win the items that i add Piggy Custom enchant in config the items wont show piggy custom enchant on the item

**Comment by IonicSyz1823** [comment]
it like Piggy custom enchant dont register onto that item, i even try with sword and armor

**Comment by JackMD** [comment]
I can't test this at the moment due to Windows 10 updates. -_-

**Comment by IonicSyz1823** [comment]
oh lol

**Comment by JackMD** [comment]
ok confirmed. I reproduced it.

**Comment by JackMD** [comment]
@IonicSyz1823 its fixed now. Thanks for the report. Report again if you have any more issues.
