### ISSUE TITLE
No Crate Inventory View

### ISSUE THREAD

**Issue by Haxley** [JackMD/MysteryCrate#32]
Claiming a crate doesn't open the chest inventory UI to show the slot machine animation as pictured in the video. There is a delay when opening the crate before receiving your reward and when the crate is destroyed, items and vines drop. This is to say the slot-machine mechanic still seems to be taking place, but something is preventing the chest from opening so the player can see it.

**Comment by JackMD** [comment]
From what I can imagine is that
Either:
 - PocketMine's spawn protection is interfering. Stop the server and set `spawn-protection` to -1 in server.properties
 - You have a land/world protection plugin that is interfering. Try testing without the protection plugin.

**Comment by JackMD** [comment]
Let me know if this commit fixed the issue. Either way the causes are mentioned above.

**Comment by Haxley** [comment]
Thanks, that seemed to fix it.

**Comment by Haxley** [comment]
Identified EssentialsPE as cause of this problem.

**Comment by JackMD** [comment]
Okay
