### ISSUE TITLE
Can remove items from crate during shuffle. 

### ISSUE THREAD

**Issue by Haxley** [JackMD/MysteryCrate#33]
During the slot-machine-like shuffle, you can select the items inside the crate and move them into your inventory.

**Comment by JackMD** [comment]
Outcome of the latest commit. Will have to revert it...

**Comment by JackMD** [comment]
And the issue you previously mentioned is due to the land/world protection plugin not cancelling interact event.

**Comment by JackMD** [comment]
I don't know about Windows 10 but on Android everything works fine. Please test without other plugins

**Comment by Haxley** [comment]
It's actually no problem. Tried it on iOS and couldn't do it. Thought then maybe it's a client-side visual glitch on PC and turns out that's exactly what it is. Items disappear on relog, works fine.

**Comment by JackMD** [comment]
Hmm I will need to test rhis first
