### ISSUE TITLE
Unknown Command when Key Used

### ISSUE THREAD

**Issue by Haxley** [JackMD/MysteryCrate#35]
When I use (right or left click while holding) a key, regardless of whether I "use" it on a chest or not, it says the generic "Unknown command. Try /help for a list of commands" error.

**Comment by JackMD** [comment]
@Haxley can you send me your plugins list

**Comment by JackMD** [comment]
I have tested it and this doesn't happen to me.

**Comment by Haxley** [comment]
Latest PocketMine-MP Release 1.7dev-1001
Plugins (32): DevTools v1.12.10, VanillaEnchantments v3.0.0-ALPHA11, Slapper v1.3.9, MysteryCrate v5.1.0, TimeOnline v1.0.0, BlockReset v1.1.0, AllAPILoader v1.0.0, Specter v0.5, EconomyAPI v5.7.1-5, PvPLevels v1.0, AntiSpamPro v1.4.0-2, TopVoter v2.3.1, FormAPI v1.1, SlapperPlus v1.0.2, EssentialsPE v2.0.0, EffectOrb v1.0.0, PurePerms v1.4.1-4, MagicTelePortal v1.3.2-3, TreasureChest v1.2.1-5, AreaEffects v1.2.0, iProtector v3.1.0-10, CombatLogger v0.0.4, BasicHUD v1.0.6-4, BanItem v2.3.2-2.alpha8, PlayerHead v2.0.0-beta, CommandShop v1.0.0, BoostPad v1, KillStreaks v1.2.0, NoFallDamage v1.0.0, PureChat v1.4.10-5, BlockSniper v2.3.1, PureChatExtras v0.1.0

**Comment by Haxley** [comment]
Identified EssentialsPE as cause of this problem.

**Comment by JackMD** [comment]
Okay
