### ISSUE TITLE
Crates Reload Facing West

### ISSUE THREAD

**Issue by Haxley** [JackMD/MysteryCrate#36]
After first use of a crate it reloads facing West.

**Comment by JackMD** [comment]
I am aware of this. I will be implementing checks to fix this soon.

**Comment by JackMD** [comment]
@Haxley there it is. The crates should reload fine now.

**Comment by Haxley** [comment]
Nice, works great.

**Comment by Haxley** [comment]
Question regarding crates: What is the last `amount` variable near the bottom of each crate in crates.yml?

**Comment by JackMD** [comment]
I thought I removed that. Anyway it was a typo.
