### ISSUE TITLE
Particle (Question Not Issue)

### ISSUE THREAD

**Issue by GageGamesHD** [JackMD/MysteryCrate#46]
Hello Jack,

Could you please start working on particles on the crates? I think this will be even more improved when particles are a thing. Maybe particles circling the crate? Or something like that

Best regards,
Gage

**Comment by JackMD** [comment]
If you look at #34 its already planned.

**Comment by JackMD** [comment]
@GageGamesHD what you requested has been added. Update your plugin version.
