### ISSUE TITLE
Im having trouble.

### ISSUE THREAD

**Issue by UnendingApple** [JackMD/MysteryCrate#51]
The crates aren't working. Like it says the crate was made and it says to restart the server so I do, but after that the floating text doesn't work, and the crate doesn't respond to my left clicking. Please help.

**Comment by JackMD** [comment]
I cannot reproduce this. Are you sure you are following the setup correctly. Read #How To Setup in the README. And are you setting the crateWorld in the config.yml or not?

**Comment by UnendingApple** [comment]
Yes I read it over three times. Also I added the world name in the
config.yml file too.

**Comment by JackMD** [comment]
Do you get any errors on console?

**Comment by UnendingApple** [comment]
lol. I'm so sorry. I set the wrong world name. I thought it was Factions76 but I miss set it to spawn, sorry for wasting your time.

**Comment by JackMD** [comment]
It appears to me as if you are not doing something right. I cannot reproduce this at all. And are you using PocketMine-MP or no?

**Comment by JackMD** [comment]
Okay. Glad you figured out the problem

**Comment by UnendingApple** [comment]
just saying, great plugin btw.

**Comment by UnendingApple** [comment]
any plans (future plugin ideas)

**Comment by JackMD** [comment]
I really don't know. Maybe and maybe not. I am working on tons of other private projects and get little to no time to make other. These latest updates for the MysteryCrate were scheduled a month back. But it kept on getting delayed time and time again.
