### ISSUE TITLE
NOTICE!!

### ISSUE THREAD

**Issue by UnendingApple** [JackMD/MysteryCrate#52]
Crates aren't fool proof. I can grab items from crates while opening one and keep the item.

**Comment by JackMD** [comment]
I cannot reproduce this at all.

**Comment by UnendingApple** [comment]
what do you mean reproduce?

**Comment by JackMD** [comment]
All I can say is that you might have another plugin interfering with inventory transactions

**Comment by JackMD** [comment]
Reproduce means it doesn't occur to me when I tested.

**Comment by JackMD** [comment]
Either you have another plugin interfering with inventory transactions or your server is suffering from lag.

**Comment by UnendingApple** [comment]
My server isn't laggy. I'm on Win10, Wby? that could cause a difference, the item disappears if I hold it too long but if I put it in inventory quick enough it allows me to keep the item.

**Comment by JackMD** [comment]
I am on Windows 10 too. But I have never faced the error even when I force try to keep the item in my inventory. Even if it comes to the inventory it is removed as soon as you click on it

**Comment by UnendingApple** [comment]
NVM. I tried throwing the items on the ground and they disappeared. My bad again.

**Comment by JackMD** [comment]
Okay thanks for reporting
