### ISSUE TITLE
Creating Cates

### ISSUE THREAD

**Issue by cosmicAtom** [JackMD/MysteryCrate#53]
Hey, how do i create a crate as there is no command

**Comment by GageGamesHD** [comment]
Alright buddy,

In the config file of the crates, under the crates in the config, you should see something called the block id. You place that block down on the ground then place a chest on top of it and it creates the crate.

**Comment by cosmicAtom** [comment]
what about adding different crates?

**Comment by GageGamesHD** [comment]
Same concept. If you want to add a custom crate, copy one of the crate's config then just change the name of the crate to your liking and change the block id to anything as long as it isn't the same id of another crate's block.

**Comment by JackMD** [comment]
@cosmicAtom please read the README. Each and everything regarding how to setup crates and how to add particles etc is there. Further @GageGamesHD explained very well. Also do mention the `crateWorld:` in the config.yml or else the crates won't work.
