### ISSUE TITLE
Hey Jack

### ISSUE THREAD

**Issue by GageGamesHD** [JackMD/MysteryCrate#54]
Hey JackMD, 

I would love to help you solve issues on this repo. I love to help people and I know a lot about your crate plugin. Is there a way you can give me access to closing issues and tagging them? I would love to take stress off your shoulders and help you with the issues so you don't have to reply to them

Best Regards, 
Gage

**Comment by JackMD** [comment]
Thanks but there isn't a way to grant you access to only closing issues and etc. I will be making a discord soon and you may as well still comment/help the people but for the most I will handle the rest
