### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by NGGNewGen** [JackMD/MysteryCrate#55]
Hi! So i am just here to give a couple of suggestions to the crates plugin :)

1. Add a line into the floating text with \n (in blocks .yml) 
2. Add multiple commands to an item in the crates (because i noticed we can only add one sadly)
3. I dont know if this is possible, but maybe you could add it to where the floating text could change colors. like transition from blue to red to green in game
Thats all of my suggestions for now but i will probably think of some more in the near future!

**Comment by JackMD** [comment]
You can already add new lines using \n. I will add compatiblity for multiple commands when I get time. And  I won't be adding multiple color or whatever that is. To much work over nothing...

**Comment by JackMD** [comment]
Also this should had been in #34

**Comment by NGGNewGen** [comment]
Oh! Sorry heh I didnt know the last one will be a lot of work and thanks for informing me i can do lines with \n already :P I appreciate you reading the suggestions! :)

**Comment by JackMD** [comment]
Multiple commands will not be implemented.

**Comment by JackMD** [comment]
@NGGNewGen multiple commands are now added. Update to latest
