### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by RawrTheGoat** [JackMD/MysteryCrate#60]
In the “How to Set Up” tab, it says to change the block of the crate in crates.yml. But I can’t find where to change it/don’t understand. Thanks!

**Comment by JackMD** [comment]
You need not to do anything just leave it as it is.

**Comment by RawrTheGoat** [comment]
Also another confusion, when I place down the chest on the block and I reload the server, I can’t open it with the crate key and floating text doesn’t spawn.

**Comment by JackMD** [comment]
On which block did you put the chest. If you are using the default crates.yml file then place the chest on top of coal, iron, gold, diamond and emerald blocks. Place a single chest on single block. Also do set the `crateWorld` in the config.yml

**Comment by RawrTheGoat** [comment]
I placed a single chest on an emerald block. But since you can edit plugin through PMMP that’s what I’ve been doing. How exactly do you get the folder name of the world? I found another issue like this and tried to change the folder name but, I don’t know where to get the folder name.

**Comment by JackMD** [comment]
Rip then...
