### ISSUE TITLE
Sorry to be annoying but...

### ISSUE THREAD

**Issue by RawrTheGoat** [JackMD/MysteryCrate#62]
I apologize for being annoying but I have searched everywhere and asked multiple people this question. Some didn’t respond and some didn’t know. So how do you get a world’s folder name (on mobile) or do I have to use a PC? Once again I apologize for being annoying.

**Comment by RawrTheGoat** [comment]
How do I open the server directory on mobile?

**Comment by JackMD** [comment]
@RawrTheGoat this is not a support forum. Ask the question on PocketMine forums. forums.pmmp.io to be exact.
