### ISSUE TITLE
Names with spaces

### ISSUE THREAD

**Issue by ManiakMCPE** [JackMD/MysteryCrate#64]
So, now that spaces are allowed in names, players can abuse this. If a user has a name like "a 99999999" and they open a crate with say $1000 as a reward, it will instead give them $99999999 because the player's username is not "in quotation marks" so it thinks that 99999999 is the amount of money it should be giving. This is the same with many other plugins as well.

**Comment by JackMD** [comment]
@ManiakMCPE Try doing ` "givemoney "%PLAYER%" 100000"`. Idk if it would make any difference or not. I'm out of town so I can't test this at the ver moment. Try doing the above and let me knkw if it works.

**Comment by ManiakMCPE** [comment]
There can't be two sets on quotations without breaking the plugin.

**Comment by 95CivicSi** [comment]
This can be fixed in the crates.yml file by using escaped characters in the command.  I will try single quotes later.  Example

```"givemoney \"%PLAYER%\" 100000"```

**Comment by JackMD** [comment]
Closing this since it can be fixed by escaped characters. 

> This can be fixed in the crates.yml file by using escaped characters in the command. I will try single quotes later. Example `"givemoney \"%PLAYER%\" 100000"`
