### ISSUE TITLE
Won’t work

### ISSUE THREAD

**Issue by RyanTheOwner** [JackMD/MysteryCrate#69]
So, I have added some items to the crates and I looked back at it because I noticed it wasn’t working and everything seems to be fine, mind emailing me to help me fix it

**Comment by JackMD** [comment]
Did you follow the exact pattern as set in crates.yml? Either way upload your crates.yml ti pastebin.com

**Comment by ASANITA** [comment]
I have the same problem

**Comment by JackMD** [comment]
I cannit reproduce this issue. Best I can say is that you delete your crates.yml file and let the plugin generate a new one. After that edit that one. And folliw the pattern set in the crates.yml or else it won't work.
