### ISSUE TITLE
EventListener is spamming EntityLevelChangeEvent error

### ISSUE THREAD

**Issue by sanalika** [JackMD/MysteryCrate#73]
when players change level, this error becomes ;

'pocketmine\event\entity\EntityLevelChangeEvent' 'MysteryCrate v6.2.0' : Cannot send empty batch JackMD\MysteryCrate\EventListener
InvalidArgumentException: "Cannot send empty batch" (EXCEPTION) in "src/pocketmine/Server" at line 1864

Plugin seems to be working fine but this error spamming makes console crazy xd

**Comment by JackMD** [comment]
Duplicate of #59

**Comment by JackMD** [comment]
I need **Steps to Reproduce** this issue. I can't say anything until I have steps to reproduce this error

**Comment by ZandercraftGames** [comment]
Jack. I get the same error. and I beleive I can provide steps to reproduce the error.

**Comment by ZandercraftGames** [comment]
Steps:
1. Start a brand new Pocketmine-MP server.
2. Configure it correctly to ur specifications
3. Install the multiworld plugin
4. Install the EssentialsPE plugin from [here](https://poggit.pmmp.io/ci/poggit-orphanage/EssentialsPE/EssentialsPE)
5. run /mw create Test 0 Flat
6. install your plugin (MysteryCrates)
7. make a crate in the default world
8. run /mw tp Test
9. run /setwarp Test
10. run /world world
11. reboot server
12. run /warp Test (make sure the console is in debug mode)

**Comment by ZandercraftGames** [comment]
I just mostly ignore the error because I deal with a bigger error (caused by a server list sending invalid packets to my server) way more often than this one...

**Comment by ZandercraftGames** [comment]
Full debug mode of the error in this selection can be found [here](https://gist.github.com/ZandercraftGames/ef82896b692bf71ce2b8db973e823882)

**Comment by JackMD** [comment]
I will look into this matter in detail within a week

**Comment by JackMD** [comment]
fixed in `951c7cb`
