### ISSUE TITLE
 any idea how to distribute the keys?

### ISSUE THREAD

**Issue by llronaldoll** [JackMD/MysteryCrate#75]
any idea how to distribute the keys?

how distribuildas to the players, I thought of throwing drops of some block but I do not know how to do it

**Comment by JackMD** [comment]
Read the README.MD. The command to give crate key is given bold amd clear in the description.

**Comment by llronaldoll** [comment]
sorry for the badly worded question that I do not know on what occasion I could distribute the keys since it is not possible to sell a custom item in pmmp! if you can give me a hand
