### ISSUE TITLE
Multi-crate opening

### ISSUE THREAD

**Issue by ZandercraftGames** [JackMD/MysteryCrate#78]
The code for making only 1 crate able to be opened at once is flawed. If someone is opening the mythic crate, and while they are doing that someone tries to open the legendary crate they get the error saying it is in use, but then the items from the mythic crate stop circling in the gui of the person opening the mythic crate and the legendary crates contents start circling in the gui. Then the person who opened the Mythic crate, gets the Legendary crate's contents

**Comment by JackMD** [comment]
I am pretty sure that this was working fine before I rewrited stuff. Will be looking into it in a week

**Comment by JackMD** [comment]
Fixed in  951c7cb
