### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by iZeaoGamer** [JackMD/MysteryCrate#82]
Hi, I was wondering if this plugin supports unlimited crates? Or maybe create your own crates or something along those lines? Thanks.

**Comment by JackMD** [comment]
Well if you could read the `README.MD` or [#features](https://github.com/JackMD/MysteryCrate#features) in the readme then you would not be asking such a question. 

To cut it short.. Yes you can create multiple crates, now please read the readme on how to set it for using multiple crates to be exact then read the **bullet # 5**

**Comment by iZeaoGamer** [comment]
You mean unlimited crates? As that’s the question I was asking. So read before answering an incorrect question.

**Comment by JackMD** [comment]
Please go and search whats the meaning of multiple.
