### ISSUE TITLE
Spam click items in crate Glitch

### ISSUE THREAD

**Issue by Zedstar16** [JackMD/MysteryCrate#83]
More than one item can be taken from the crate at any one usage,
Steps to reproduce:
1) Open crate with about 10+ items inside
2) as items start to move, spam click the moving ones inside the chest. They will go in your inv but most will go back to the crate -however some stay. The ones that stay usually disappear after 2-3s.
3) when the rotation cycle ends, any items in the inventory that have not gone back to the crate will stay in the players inventory as well as the item legitimately won from the crate.
4) Either relog on the server or put the items inside an ender chest, on reopening the ender chest/ coming back on to the server, the glitched items from the crate will remain in a players inv

**Comment by JackMD** [comment]
This is not the plugins fault for this problem. Nor do I think its server sided (could be but idk for sure), its client sided.

**Comment by zKoz210** [comment]
@JackMD You can use this method to fix the problem. First set all the items in the chest and then send the information about them to the customer, it works 😄 

```
$this->chest->getInventory()->setItem($index, $item, false);
$this->chest->getInventory()->setItem($index2, $item2, false); // and more
$this->chest->getInventory()->sendContents($player);
```

**Comment by JackMD** [comment]
This is now fixed.
