### ISSUE TITLE
Fix Piggy Custom Enchants

### ISSUE THREAD

**Issue by ZandercraftGames** [JackMD/MysteryCrate#89]
Piggy custom enchants is no longer `PiggyCustomEnchants\Main` it is now `DaPigGuy\PiggyCustomEnchants\Main` to comply with the Poggit C1a rule. I will try to make a pull request.

**Comment by ZandercraftGames** [comment]
Nevermind You fixed this already.

**Comment by JackMD** [comment]
Reeeeeeeeeee lol
