### ISSUE TITLE
Invalid Player

### ISSUE THREAD

**Issue by timothytay** [JackMD/MysteryCrate#91]
When I /key [type] [player] [amount] , it tells me "Invalid Player" even when I specifically copy pasted the exact player name capitals included.

**Comment by JackMD** [comment]
is the player even online?

**Comment by JackMD** [comment]
anyway it works fine for me

**Comment by timothytay** [comment]
The player is myself.

**Comment by timothytay** [comment]
Yes I was online.

**Comment by JackMD** [comment]
If you want to give it to yourself then you can simply do `/key [type]` and it will give you the key
