### ISSUE TITLE
[Suggestion] Disable Customname

### ISSUE THREAD

**Issue by SchdowNVIDIA** [JackMD/MysteryCrate#96]
Hey,

My suggestion is to remove the customname via an extra tag maybe like:
c-name: false/true

Well for some Items there is no need for a rename.

best regards,
SchdowNVIDIA

**Comment by JackMD** [comment]
I thought of doing it a while ago but never went on completing it. Will implement it when I get time 😀

**Comment by SchdowNVIDIA** [comment]
That would be nice!

**Comment by JackMD** [comment]
Issue is now fixed. Further now you dont need to set `name` key in crates.yml. Only add it when you want to add custom name to the item
