### ISSUE TITLE
[Bug?] Users can only open 1 chest at once.

### ISSUE THREAD

**Issue by SchdowNVIDIA** [JackMD/MysteryCrate#98]
Hey,

Idk if that is a bug but my players can only open 1 chest the anvil or the vote chest:
![grafik](https://user-images.githubusercontent.com/39440218/51440337-5c59c480-1cc6-11e9-996f-f1650cf72922.png)

Can you fix that?

Best regards,
SchdowNVIDIA

**Comment by JackMD** [comment]
Thats not a bug. Thats an intended behavior

**Comment by JackMD** [comment]
However I have plans to make it work for many users at the same time but on a later date

**Comment by JackMD** [comment]
Now users can open multiple crates 😄

**Comment by SchdowNVIDIA** [comment]
Nice man! Great job!!

**Comment by JackMD** [comment]
😀
